apiVersion: v1
kind: bgpPeer
metadata:
  scope: node
  node: 127.0.0.1
  peerIP: 192.168.1.1
spec:
  asNumber: 63400

---

apiVersion: v1
kind: bgpPeer
metadata:
  scope: global
  peerIP: 192.168.1.2
spec:
  asNumber: 63400

---

apiVersion: v1
kind: ipPool
metadata:
  cidr: 10.1.0.0/16
spec:
  ipip:
    enabled: true
    mode: cross-subnet

---

apiVersion: v1
kind: ipPool
metadata:
  cidr: 10.2.0.0/16
spec:
  ipip:
    enabled: false
  nat-outgoing: true

---

apiVersion: v1
kind: ipPool
metadata:
  cidr: 10.3.0.0/16
spec:
  ipip:
    enabled: true
    mode: always
  nat-outgoing: true
  disabled: true

---

apiVersion: v1
kind: ipPool
metadata:
  cidr: 10.4.0.0/16
spec:
  disabled: true

